### ISSUE TITLE
HqOsu on latest osu release 20201210.2

### ISSUE THREAD

**Issue by AwesomeGamer89** [Hazuki-san/hqOsu-xtreme#7]
Checking for updates...
Downloading hqOsu.Loader.exe...
Downloading hqOsu.Passport.Generator.exe...

Unhandled Exception: System.InvalidOperationException: SetCompatibleTextRenderingDefault must be called before the first IWin32Window object is created in the application.
   at System.Windows.Forms.Application.SetCompatibleTextRenderingDefault(Boolean defaultValue)
   at hqOsu.Loader.Loader.Main()
   at hqOsu.Loader.Loader.Main()

**Comment by Hazuki-san** [comment]
#6
